### ISSUE TITLE
Dumping device code

### ISSUE THREAD

**Issue by nilclass** [animaone/macrosilicon_reverse_engineering_journey#1]
Hey there, great project! I've also wanted to buy a FL2000 based device, and ended up with a MS9120.
Your work is a great start for me to try to do something useful with it, thank you for sharing!

Quoting from the README:
> I managed to dump the device code (will describe this other not-so-trivial trick later)

Could you share this trick? I'm curious to see what the device is capable of. If you could share the device's code itself, that would be superb too.

For clarity: I'm not trying to use this device as a USB to VGA, but rather as a fast digital-to-analog converter, for radio purposes (like the osmocom project [does with the FL2000](https://osmocom.org/projects/osmo-fl2k/wiki))

**Comment by animaone** [comment]
I have good and bad news about that.
The good is that I will save you some time
The bad is that this macrosilicon IC is a framebuffer, kind of an external video card with "lots" of RAM, in fact what makes the IC big (if you check the pcb) is this colossal amount of RAM.
The fl2k ics are totally different, they even have a patent for their way of working (everything is processed before the usb connection and sent out to the output, which makes it kind of perfect for doing SDR stuff).
You can use ms210x-tools to examine the hardware's memory, if you still want to do something with it. It is well documented by the community, but not by Macrosilicon. If I remember correctly, there is even a framebuffer driver for Linux.

**Comment by nilclass** [comment]
I was able to dump the memory, but haven't gotten anywhere trying to figure out what's in there. I was hoping there to be some executable code, assuming there is some sort of MCU on the chip. So far I haven't found out anything useful though.

Could you clarify: when you said you managed to "dump the device code", did you mean you dumped the memory contents, or did you actually find code that disassembles to something reasonable?

> It is well documented by the community

do you happen to have a link to that documentation? I could not find any info.

**Comment by animaone** [comment]
lol.
